pin-2686: Improve keys creation errors
pagopa/interop-be-authorization-management pull request #197
Opened 2023-02-06 17:11 UTC by galales

2023-02-06 17:49 UTC, beetlecrunch commented on src/main/scala/it/pagopa/interop/authorizationmanagement/model/persistence/impl/Validation.scala
>        // _   <- KeyProcessor.usableJWK(jwk)
This function is used only here (commented).
Probably we can remove it.

2023-02-06 17:49 UTC, beetlecrunch approved these changes

2023-02-07 08:12 UTC, TonioGela requested changes
LGTM

2023-02-07 08:12 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/authorizationmanagement/model/persistence/impl/Validation.scala
> +      case l   => Left(KeysAlreadyExist(l))
```suggestion
    Either.right(existingIds).ensureOr(l => KeysAlreadyExist(l))(_.isEmpty)
```

2023-02-07 09:04 UTC, TonioGela approved these changes

2023-02-07 09:05 UTC, merged